"""create V1 domain schema

Revision ID: 15ac772ee7c5
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from backend.app.models import UTCDateTime

revision: str = "15ac772ee7c5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("stable_identifier", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stable_identifier"),
    )
    op.create_table(
        "data_bundles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider_name", sa.String(length=255), nullable=False),
        sa.Column("plan_name", sa.String(length=255), nullable=False),
        sa.Column("allowance_bytes", sa.BigInteger(), nullable=False),
        sa.Column("billing_cycle_start", UTCDateTime(), nullable=False),
        sa.Column("billing_cycle_end", UTCDateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint("allowance_bytes > 0", name="ck_bundle_allowance_positive"),
        sa.CheckConstraint("billing_cycle_end > billing_cycle_start", name="ck_bundle_time_order"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_bundle_provider_created", "data_bundles", ["provider_name", "created_at"], unique=False
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("operating_system", sa.String(length=100), nullable=False),
        sa.Column("operating_system_version", sa.String(length=100), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hostname"),
    )
    op.create_table(
        "traffic_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider_type", sa.String(length=100), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("scope", sa.String(length=255), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("monotonic", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("provider_version", sa.String(length=100), nullable=True),
        sa.Column("source_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "domain IN ('measured.interface', 'attributed.process', "
            "'measured.gateway_wan', 'attributed.device')",
            name="ck_traffic_source_domain",
        ),
        sa.CheckConstraint("unit = 'bytes'", name="ck_traffic_source_unit"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_type", "name", "scope", name="uq_traffic_source_identity"),
    )
    op.create_table(
        "application_usage",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("bucket_start", UTCDateTime(), nullable=False),
        sa.Column("bucket_end", UTCDateTime(), nullable=False),
        sa.Column("received_bytes", sa.BigInteger(), nullable=False),
        sa.Column("transmitted_bytes", sa.BigInteger(), nullable=False),
        sa.Column("quality", sa.String(length=50), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint("bucket_end > bucket_start", name="ck_application_usage_time_order"),
        sa.CheckConstraint("received_bytes >= 0", name="ck_application_rx_nonnegative"),
        sa.CheckConstraint("transmitted_bytes >= 0", name="ck_application_tx_nonnegative"),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["traffic_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_application_usage_time",
        "application_usage",
        ["application_id", "bucket_start"],
        unique=False,
    )
    op.create_table(
        "collector_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("started_at", UTCDateTime(), nullable=False),
        sa.Column("ended_at", UTCDateTime(), nullable=True),
        sa.Column("collector_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("health_metadata", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["traffic_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_collector_run_source_started",
        "collector_runs",
        ["source_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "counter_series",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("identity", sa.String(length=255), nullable=False),
        sa.Column("accounting_domain", sa.String(length=50), nullable=False),
        sa.Column("scope", sa.String(length=255), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "accounting_domain IN ('measured.interface', 'attributed.process', "
            "'measured.gateway_wan', 'attributed.device')",
            name="ck_counter_series_domain",
        ),
        sa.CheckConstraint(
            "direction IN ('download', 'upload')", name="ck_counter_series_direction"
        ),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["traffic_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id",
            "device_id",
            "direction",
            "identity",
            "accounting_domain",
            "scope",
            name="uq_counter_series_identity",
        ),
    )
    op.create_index(
        "ix_counter_series_source_device",
        "counter_series",
        ["source_id", "device_id"],
        unique=False,
    )
    op.create_table(
        "data_audit_experiments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("data_bundle_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("measurement_source_id", sa.String(length=36), nullable=True),
        sa.Column("measurement_boundary", sa.String(length=100), nullable=False),
        sa.Column("started_at", UTCDateTime(), nullable=True),
        sa.Column("ended_at", UTCDateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("methodology_version", sa.String(length=100), nullable=False),
        sa.Column("user_notes", sa.Text(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'completed', 'cancelled')",
            name="ck_experiment_status",
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR started_at IS NOT NULL AND ended_at >= started_at",
            name="ck_experiment_time_order",
        ),
        sa.ForeignKeyConstraint(["data_bundle_id"], ["data_bundles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["measurement_source_id"], ["traffic_sources.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_experiment_status_created",
        "data_audit_experiments",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "counter_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("counter_series_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp_utc", UTCDateTime(), nullable=False),
        sa.Column("monotonic_timestamp_ns", sa.BigInteger(), nullable=False),
        sa.Column("raw_counter_bytes", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("sequence_key", sa.String(length=255), nullable=False),
        sa.Column("collector_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint("raw_counter_bytes >= 0", name="ck_observation_bytes_nonnegative"),
        sa.ForeignKeyConstraint(["counter_series_id"], ["counter_series.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "counter_series_id", "session_id", "sequence_key", name="uq_observation_idempotency"
        ),
    )
    op.create_index(
        "ix_observation_series_timestamp",
        "counter_observations",
        ["counter_series_id", "timestamp_utc"],
        unique=False,
    )
    op.create_table(
        "isp_balance_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp_utc", UTCDateTime(), nullable=False),
        sa.Column("reported_value", sa.String(length=100), nullable=False),
        sa.Column("reported_unit", sa.String(length=30), nullable=False),
        sa.Column("snapshot_type", sa.String(length=50), nullable=False),
        sa.Column("normalized_bytes", sa.BigInteger(), nullable=True),
        sa.Column("provenance", sa.String(length=50), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("correction_of_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "normalized_bytes IS NULL OR normalized_bytes >= 0", name="ck_snapshot_bytes"
        ),
        sa.CheckConstraint("provenance = 'manual'", name="ck_snapshot_provenance"),
        sa.CheckConstraint(
            "snapshot_type IN ('remaining_balance', 'cumulative_consumption')",
            name="ck_snapshot_type",
        ),
        sa.ForeignKeyConstraint(
            ["correction_of_snapshot_id"], ["isp_balance_snapshots.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["data_audit_experiments.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_snapshot_experiment_timestamp",
        "isp_balance_snapshots",
        ["experiment_id", "timestamp_utc"],
        unique=False,
    )
    op.create_table(
        "measurement_discontinuities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=True),
        sa.Column("counter_series_id", sa.String(length=36), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("start_timestamp", UTCDateTime(), nullable=False),
        sa.Column("end_timestamp", UTCDateTime(), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint("end_timestamp > start_timestamp", name="ck_discontinuity_time_order"),
        sa.ForeignKeyConstraint(["counter_series_id"], ["counter_series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["data_audit_experiments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["source_id"], ["traffic_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_discontinuity_experiment_time",
        "measurement_discontinuities",
        ["experiment_id", "start_timestamp"],
        unique=False,
    )
    op.create_table(
        "usage_intervals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("counter_series_id", sa.String(length=36), nullable=False),
        sa.Column("start_timestamp", UTCDateTime(), nullable=False),
        sa.Column("end_timestamp", UTCDateTime(), nullable=False),
        sa.Column("delta_bytes", sa.BigInteger(), nullable=False),
        sa.Column("quality", sa.String(length=50), nullable=False),
        sa.Column("discontinuity_reason", sa.String(length=100), nullable=True),
        sa.Column("methodology_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint("delta_bytes >= 0", name="ck_usage_delta_nonnegative"),
        sa.CheckConstraint("end_timestamp > start_timestamp", name="ck_usage_time_order"),
        sa.ForeignKeyConstraint(["counter_series_id"], ["counter_series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "counter_series_id",
            "start_timestamp",
            "end_timestamp",
            "methodology_version",
            name="uq_usage_interval_derivation",
        ),
    )
    op.create_index(
        "ix_usage_interval_series_time",
        "usage_intervals",
        ["counter_series_id", "start_timestamp"],
        unique=False,
    )
    op.execute(
        """
        CREATE TRIGGER counter_observations_immutable_update
        BEFORE UPDATE ON counter_observations
        BEGIN SELECT RAISE(ABORT, 'counter observations are immutable'); END
        """
    )
    op.execute(
        """
        CREATE TRIGGER counter_observations_immutable_delete
        BEFORE DELETE ON counter_observations
        BEGIN SELECT RAISE(ABORT, 'counter observations are immutable'); END
        """
    )
    op.execute(
        """
        CREATE TRIGGER isp_snapshots_immutable_update
        BEFORE UPDATE ON isp_balance_snapshots
        BEGIN SELECT RAISE(ABORT, 'ISP snapshots are immutable; create a correction'); END
        """
    )
    op.execute(
        """
        CREATE TRIGGER isp_snapshots_immutable_delete
        BEFORE DELETE ON isp_balance_snapshots
        BEGIN SELECT RAISE(ABORT, 'ISP snapshots are immutable; create a correction'); END
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS isp_snapshots_immutable_delete")
    op.execute("DROP TRIGGER IF EXISTS isp_snapshots_immutable_update")
    op.execute("DROP TRIGGER IF EXISTS counter_observations_immutable_delete")
    op.execute("DROP TRIGGER IF EXISTS counter_observations_immutable_update")
    op.drop_index("ix_usage_interval_series_time", table_name="usage_intervals")
    op.drop_table("usage_intervals")
    op.drop_index("ix_discontinuity_experiment_time", table_name="measurement_discontinuities")
    op.drop_table("measurement_discontinuities")
    op.drop_index("ix_snapshot_experiment_timestamp", table_name="isp_balance_snapshots")
    op.drop_table("isp_balance_snapshots")
    op.drop_index("ix_observation_series_timestamp", table_name="counter_observations")
    op.drop_table("counter_observations")
    op.drop_index("ix_experiment_status_created", table_name="data_audit_experiments")
    op.drop_table("data_audit_experiments")
    op.drop_index("ix_counter_series_source_device", table_name="counter_series")
    op.drop_table("counter_series")
    op.drop_index("ix_collector_run_source_started", table_name="collector_runs")
    op.drop_table("collector_runs")
    op.drop_index("ix_application_usage_time", table_name="application_usage")
    op.drop_table("application_usage")
    op.drop_table("traffic_sources")
    op.drop_table("devices")
    op.drop_index("ix_bundle_provider_created", table_name="data_bundles")
    op.drop_table("data_bundles")
    op.drop_table("applications")
    # ### end Alembic commands ###
